model:
    name: 'RidgeRULPredictor'
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/HNEI'
        - 'data/processed/MATR'
        - 'data/processed/HUST'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 9
    max_cycle_index: 99
    cycles_to_keep: 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
