model:
    features_to_drop: [1, 3, 4, 5]
    name: 'BatLiNetRULPredictor'
    in_channels: 2
    channels: 32
    input_height: 100
    input_width: 1000
    epochs: 1000
    train_batch_size: 128
    test_batch_size: 1
    train_support_size: 1
    test_support_size: 32
    gradient_accumulation_steps: 1
    evaluate_freq: 100
    checkpoint_freq: None
    diff_base: 9
    alpha: 0.2
train_test_split:
    name: 'MATRSecondaryTestTrainTestSplitter'
    cell_data_path: 'data/processed/MATR'
feature:
    name: 'BatLiNetFeatureExtractor'
    smooth_features: False
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
