model:
    name: 'BatLiNetRULPredictor'
    in_channels: 6
    channels: 32
    input_height: 100
    input_width: 1000
    epochs: 1000
    train_batch_size: 128
    test_batch_size: 1
    train_support_size: 2
    test_support_size: 32
    gradient_accumulation_steps: 1
    evaluate_freq: 100
    checkpoint_freq: 2000
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path:
      - 'data/processed/CALCE'
      - 'data/processed/RWTH'
      - 'data/processed/UL_PUR'
      - 'data/processed/HNEI'
      - 'data/processed/MATR'
      - 'data/processed/HUST'
feature:
    name: 'BatLiNetFeatureExtractor'
    smooth_features: False
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
      - name: 'LogScaleDataTransformation'
      - name: 'ZScoreDataTransformation'
