model:
    name: 'BatLiNetRULPredictor'
    in_channels: 6
    channels: 32
    input_height: 20
    input_width: 1000
    epochs: 1000
    train_batch_size: 128
    test_batch_size: 1
    train_support_size: 4
    test_support_size: 32
    gradient_accumulation_steps: 1
    diff_base: 0
    evaluate_freq: 100
    checkpoint_freq: None
    filter_cycles: False
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/SNL'
        - 'data/processed/MATR'
        - 'data/processed/HUST'
        - 'data/processed/HNEI'
feature:
    name: 'BatLiNetFeatureExtractor'
    max_cycle_index: 19
    cycle_to_drop: 10
    smooth_features: False
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.9
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
