from .cnn import CNNRULPredictor
from .mlp import MLPRULPredictor
from .pcr import PCRRULPredictor
from .svm import SVMRULPredictor
from .lstm import LSTMRULPredictor
from .plsr import PLSRRULPredictor
from .elastic_net import ElasticNetRULPredictor
from .random_forest import RandomForestRULPredictor
from .linear_regression import LinearRegressionRULPredictor
from .batlinet import BatLiNetRULPredictor
from .dummy import DummyRULPredictor
from .ridge import RidgeRULPredictor
from .gaussian_process import GaussianProcessRULPredictor
from .cell_diff_cnn import CellDifferenceCNNRULPredictor
from .cycle_diff_cnn import CycleDifferenceCNNRULPredictor
from .naive_diff_cnn import NaiveDifferenceCNNRULPredictor
