model:
    name: 'PCRRULPredictor'
    n_components: 2
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/SNL'
        - 'data/processed/MATR'
        - 'data/processed/HUST'
        - 'data/processed/HNEI'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 0
    max_cycle_index: 19
    cycles_to_keep: 19
label:
    name: 'RULLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        # - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'