model:
    name: 'HybridDifferenceCNNRULPredictor'
    in_channels: 2
    features_to_drop: [2, 3, 4, 5]
    channels: 32
    input_height: 100
    input_width: 1000
    epochs: 1000
    train_batch_size: 128
    test_batch_size: 1
    train_support_size: 2
    test_support_size: 32
    gradient_accumulation_steps: 1
    evaluate_freq: 100
    checkpoint_freq: None
    alpha: 0.7
train_test_split:
    name: 'HUSTTrainTestSplitter'
    cell_data_path: 'data/processed/HUST'
feature:
    name: 'MultifacetedCapacityMatrixRULFeatureExtractor'
    smooth_features: False
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
