model:
    name: 'BatLiNetRULPredictor'
    in_channels: 6
    channels: 32
    input_height: 100
    input_width: 1000
    epochs: 1000
    train_batch_size: 8
    test_batch_size: 1
    train_support_size: 32
    test_support_size: 32
    gradient_accumulation_steps: 16
    evaluate_freq: 100
    alpha: 0.2
    checkpoint_freq: None
train_test_split:
    name: 'MATRSecondaryTestTrainTestSplitter'
    cell_data_path: 'data/processed/MATR'
feature:
    name: 'BatLiNetFeatureExtractor'
    smooth_features: False
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
